name: Deploy Theme

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to DigitalOcean via rsync
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{ secrets.DIGITALOCEAN_HOST }}
        username: ${{ secrets.DIGITALOCEAN_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          set -x  # Enable command tracing

          # Print current directory
          echo "Current directory:"
          pwd

          # Print files in the current directory
          echo "Files in the current directory:"
          ls -la

          # Test SSH connection and print success
          echo "Testing SSH connection..."
          ssh -o StrictHostKeyChecking=no -T ${{ secrets.DIGITALOCEAN_USERNAME }}@${{ secrets.DIGITALOCEAN_HOST }} "echo SSH connection successful"

          # Print confirmation
          echo "New theme files deployed."
