name: Deploy Theme

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Composer
      run: |
        curl -sS https://getcomposer.org/installer | php
        sudo mv composer.phar /usr/local/bin/composer

    - name: Clean vendor and install dependencies
      run: |
        rm -rf ./vendor
        composer install --optimize-autoloader

    - name: Build project and list contents
      run: |
        npm install
        npm run build:production
        ls -l
        ls -l ./dist  # Check contents of dist folder if necessary

    - name: Save build assets as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: theme
        path: .  # Upload everything from the current directory

    - name: Debugging - List workspace contents
      run: |
        ls -la ${{ github.workspace }}
    - name: Deploy to VPS via rsync
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SOURCE: "./"
        REMOTE_HOST: ${{ secrets.DIGITALOCEAN_HOST }}
        REMOTE_USER: ${{ secrets.DIGITALOCEAN_USERNAME }}
        TARGET: "/var/www/html/wp-content/themes/betseige"

