name: Deploy Theme

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Composer
      run: |
        curl -sS https://getcomposer.org/installer | php
        sudo mv composer.phar /usr/local/bin/composer

    - name: Clean vendor and install dependencies
      run: |
        # Navigate to theme directory
        cd wp-content/themes/betseige
        # Remove vendor folder included in the repository
        rm -rf ./vendor
        # Install dependencies
        composer install --optimize-autoloader

    - name: Save vendor directory as artifact
      uses: actions/upload-artifact@v3
      with:
        name: vendor
        path: wp-content/themes/betseige/vendor/

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.11.1'

    - name: Build project assets
      run: |
        # Navigate to theme directory
        cd wp-content/themes/betseige
        # Install node dependencies and build assets
        npm install
        npm run build:production

    - name: Save build assets as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: wp-content/themes/betseige/dist/

    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.DIGITALOCEAN_HOST }}
        username: ${{ secrets.DIGITALOCEAN_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          set -x  # Enable command tracing

          # Delete node_modules folder on the server
          echo "Deleting node_modules folder on the server..."
          rm -rf /var/www/html/wp-content/themes/betseige/node_modules

          # Rsync files to the server
          echo "Copying new theme files using rsync..."
          rsync -zrSlh --stats ./wp-content/themes/betseige/* ${{ secrets.DIGITALOCEAN_USERNAME }}@${{ secrets.DIGITALOCEAN_HOST }}:/var/www/html/wp-content/themes/betseige

          # Install JQ if needed
          echo "Installing JQ..."
          sudo apt-get update && sudo apt-get install -y jq

          # Print confirmation
          echo "New theme files deployed."
