name: Deploy Theme

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Composer
      run: |
        curl -sS https://getcomposer.org/installer | php
        mv composer.phar /usr/local/bin/composer

    - name: Clean vendor and install dependencies
      run: |
        rm -rf ./vendor
        composer install --optimize-autoloader

    - name: Build project and list contents
      run: |
        npm install
        npm run build:production
        ls -l
        ls -l ./dist  # Check contents of dist folder if necessary

    - name: Save build assets as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: theme
        path: .  # Upload everything from the current directory

    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.DIGITALOCEAN_HOST }}
        username: ${{ secrets.DIGITALOCEAN_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          set -x  # Enable command tracing

          # Ensure the destination directory exists
          mkdir -p /var/www/html/wp-content/themes/betseige

          # Rsync files to the server
          rsync -zrSlh --stats /home/runner/work/betseige/betseige/ root@134.209.212.21:/var/www/html/wp-content/themes/betseige

          # Print confirmation
          echo "New theme files deployed."
